
/**
 * Provides methods for interacting with the backend task API
*/

import type { Task } from "./hooks/useTasks"; 

const API = import.meta.env.VITE_API_BASE || "http://localhost:3000";

export async function getTasks(): Promise<Task[]> {
  const res = await fetch(`${API}/api/tasks`);
  return res.json();
}

/**
 * Task object without _id (generated by server)
*/

export async function createTask(task: Omit<Task, "_id">): Promise<Task> {
  const res = await fetch(`${API}/api/tasks`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(task),
  });
  return res.json();
}

export async function updateTask(id: string, updates: Partial<Task>): Promise<Task> {
  const res = await fetch(`${API}/api/tasks/${id}`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(updates),
  });
  return res.json();
}

export async function deleteTaskById(id: string): Promise<void> {
  await fetch(`${API}/api/tasks/${id}`, { method: "DELETE" });
}

export async function clearCompletedTasksFromServer(): Promise<void> {
  await fetch(`${API}/api/tasks/clear-completed`, { method: "DELETE" });
}
